#!/bin/sh

# TODO: This script requires ROOT to be run in OSX
# (or just sign the r2 binary to get debugger priviledges)
# GPL 3+ - Copyright (C) 2014  pancake

. $(git rev-parse --show-toplevel)/tests.sh

NAME='dbg.readpc'
FILE=/bin/ls
ARGS=-d
BROKEN=
CMDS='sr pc
p8 4
'
NOT_EXPECT=1
EXPECT='ffffffff
'
IGNORE_ERR=1
run_test

