#!/bin/sh
. $(git rev-parse --show-toplevel)/tests.sh

NAME='PE: corkami base.exe - open'
FILE=../../bins/pe/base.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='Relocs'
FILE=../../bins/pe/base.exe
ARGS=''
CMDS='e asm.functions = false
pd 1 @ 0x0040128d~!reloc'
EXPECT=''

run_test
