#!/bin/sh
. $(git rev-parse --show-toplevel)/tests.sh

NAME='PE: corkami dep.exe - open'
FILE=../../bins/pe/dep.exe
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: corkami dep.exe - dep enabled'
FILE=../../bins/pe/dep.exe
ARGS='-n'
CMDS="!rabin2 -k 'pe.nx' ${FILE}"

EXPECT='true

'
run_test
