#!/bin/sh
. $(git rev-parse --show-toplevel)/tests.sh

NAME='PE: corkami dllnullep.dll - open'
FILE=../../bins/pe/dllnullep.dll
IGNORE_ERR=1
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: dllnullEP - entrypoint'
FILE=../../bins/pe/dllnullep.dll
BROKEN=1
IGNORE_ERR=1
ARGS='-n'
CMDS="!rabin2 -eq ${FILE} "

EXPECT='0x00000000
'

run_test


