#!/bin/sh
. $(git rev-parse --show-toplevel)/tests.sh

NAME='MZ: jman.exe - open'
FILE=../../bins/pe/jman.exe
ARGS=''
CMDS="q!"
EXPECT=''

run_test

NAME='MZ: jman.exe - entrypoint'
FILE=../../bins/pe/jman.exe
ARGS=''
BROKEN=
CMDS="pi 1"
EXPECT='mov ax, 0x2df3
'
run_test
