#!/bin/sh
. $(git rev-parse --show-toplevel)/tests.sh

NAME='PE: corkami nullEP.exe - open'
FILE=../../bins/pe/nullEP.exe
IGNORE_ERR=1
ARGS=''
CMDS="q!"
EXPECT=''
run_test

NAME='PE: nullEP - entrypoint'
FILE=../../bins/pe/nullEP.exe
IGNORE_ERR=1
BROKEN=1
ARGS='-n'
CMDS="!rabin2 -eq ${FILE} "

EXPECT='0x00000000
'

run_test


