#!/bin/sh
. $(git rev-parse --show-toplevel)/tests.sh

BROKEN=
FILE=../../bins/pe/pe.exe
CMDS='
s
'
EXPECT='0x401000
'
run_test


BROKEN=
FILE=../../bins/pe/vista-glass.exe
CMDS='q!
'
EXPECT=''

run_test
