#!/bin/sh
. $(git rev-parse --show-toplevel)/tests.sh

NAME='ELF: IOLI - crackme3 - with -A'
FILE=../../../bins/elf/ioli/crackme0x03
ARGS=
CMDS="aa ; fs symbols ; f~sym.main"
EXPECT='0x08048498 128 sym.main
'
run_test
