#!/bin/sh
. $(git rev-parse --show-toplevel)/tests.sh

NAME='ELF: IOLI - crackme7 - with -A'
FILE=../../../bins/elf/ioli/crackme0x07
ARGS='-A'
CMDS="afi 0x804867d~size"
EXPECT=' size: 99
'
run_test

NAME='ELF: IOLI - crackme7 - with aa'
FILE=../../../bins/elf/ioli/crackme0x07
ARGS=''
CMDS="aa;afi 0x804867d~size"
EXPECT=' size: 99
'
run_test
