#!/bin/sh

# GPL 3+ - Copyright (C) 2013  pancake

. $(git rev-parse --show-toplevel)/tests.sh
F=../../bins/java/ExCaseTableSwitch.class

NAME='java disasm crash'
IGNORE_ERR=1
BROKEN=
FILE=$F
ARGS=
CMDS='pd 10 >/dev/null
'
EXPECT=''
run_test

