#!/bin/sh
. $(git rev-parse --show-toplevel)/tests.sh

NAME='PE: corkami elf-xnorelro - relro disabled'
FILE=../../bins/elf/elf-xnorelro
ARGS=''
CMDS="ik~elf.relro=false"

EXPECT='elf.relro=false
'
run_test


NAME='PE: corkami elf-nx -  nx disabled'
FILE=../../bins/elf/elf-xnorelro
ARGS=''
CMDS="iI~^nx"

EXPECT='nx       false
'

run_test
