#!/bin/sh
. $(git rev-parse --show-toplevel)/tests.sh

NAME='ELF: main'
FILE=../../bins/elf/main
ARGS=''
CMDS="?v main"
EXPECT='0x400506
'
run_test

NAME='ELF: sym.main'
FILE=../../bins/elf/main
ARGS=''
CMDS="?v sym.main"
EXPECT='0x400506
'
run_test

NAME='ELF: pie main'
FILE=../../bins/elf/pie-main
ARGS=''
CMDS="?v main"
EXPECT='0x3bd0
'
run_test

NAME='MIPS: main'
FILE=../../bins/elf/mips-main
ARGS=''
CMDS="?v main"
EXPECT='0x4006f0
'
run_test
