#!/bin/sh

# GPL 3+ - Copyright (C) 2014  pancake

. $(git rev-parse --show-toplevel)/tests.sh

# "!" - run commands (via system)

NAME='uname'
FILE=-
ARGS=
BROKEN=
CMDS='
!uname
'
EXPECT='Darwin
'
run_test

