#!/bin/sh
# LGPL - Copyright (C) 2014 Fedor Sakharov

. $(git rev-parse --show-toplevel)/tests.sh

NAME="anal/fcn_name"
BROKEN=
FILE=../../bins/elf/main-g
IGNORE_ERR=1
ARGS=
CMDS='s 0x0040042c
af
pd 1~sym.call_gmon_start:0'
EXPECT='/ (fcn) sym.call_gmon_start 23
'
run_test

NAME="anal/fcn_subname"
BROKEN=
FILE=../../bins/elf/main-g
ARGS=
# REGRESSION
BROKEN=
IGNORE_ERR=1
CMDS='s 0x0040042c
af
afi~name
pd 1~sym.call_gmon_start:0'
EXPECT=' name: sym.call_gmon_start
/ (fcn) sym.call_gmon_start 23
'
run_test
