#!/bin/sh
. $(git rev-parse --show-toplevel)/tests.sh

NAME='MSIL: hello.exe - detect'
FILE=../../bins/msil/hello.exe
ARGS=''
CMDS="i~^lang[1]"
EXPECT='msil
'
run_test

NAME='MSIL: AStyleWhore.exe - detect'
FILE=../../bins/msil/AStyleWhore.exe
ARGS=''
CMDS="i~^lang[1]"
EXPECT='msil
'
run_test
